### ISSUE TITLE
dependencies for 17.10

### ISSUE THREAD

**Issue by SimonF89** [Victor-Haefner/polyvr-depends#2]
I tried to install polyvr on the new ubuntu but it misses opensg. Do you have the package for 17.10 ??

**Comment by Victor-Haefner** [comment]
hi, sorry I missed that! 
..well, better late than never..
I compile the packages for the LTS releases of ubuntu, if you want to run polyvr on another system just clone the polyvr-packaging repository and run setup_dependencies.sh, then the package scripts
